<?php

namespace MartinuxShop\EcommerceBundle\Repository;

/**
 * tvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tvaRepository extends \Doctrine\ORM\EntityRepository
{
}
